version: '3.7'

services:
  client:
    container_name: cospik_client
    build:
      context: client/.
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: cospik_api
    build:
      context: server/.
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "3110:3110"
    volumes:
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5400:5432"
    volumes:
      - ./docker/data/db:/var/lib/postgresql
