
// ADMIN ACTION CONSTANTS
export const ADMIN_SIGN_IN_REQUEST = "ADMIN_SIGN_IN_REQUEST";
export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";
export const ADMIN_SIGN_IN_FAILURE = "ADMIN_SIGN_IN_FAILURE";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAILURE = "ADMIN_REGISTER_FAILURE";
export const SET_ADMIN = "SET_ADMIN";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

// NOTIFICATIONS
export const SET_NOTIFY = "SET_NOTIFY";
export const CLOSE_NOTIFY = "CLOSE_NOTIFY";


// STUDENT CONSTANTS
export const GET_ALLSTUDENT_REQUEST = "GET_ALLSTUDENT_REQUEST";
export const GET_ALLSTUDENT_SUCCESS = "GET_ALLSTUDENT_SUCCESS";
export const GET_ALLSTUDENT_FAILURE = "GET_ALLSTUDENT_FAILURE";
export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE";
export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_FAILURE = "EDIT_STUDENT_FAILURE";
export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE";


// COURSES CONSTANTS
export const GET_ALLCOURSES_REQUEST = "GET_ALLCOURSES_REQUEST";
export const GET_ALLCOURSES_SUCCESS = "GET_ALLCOURSES_SUCCESS";
export const GET_ALLCOURSES_FAILURE = "GET_ALLCOURSES_FAILURE";
export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

// ENROLL CONSTANTS
export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE";
export const UNENROLL_COURSE_REQUEST = "UNENROLL_COURSE_REQUEST";
export const UNENROLL_COURSE_SUCCESS = "UNENROLL_COURSE_SUCCESS";
export const UNENROLL_COURSE_FAILURE = "UNENROLL_COURSE_FAILURE";